services:
    db:
        container_name: db
        image: postgres:latest
        env_file:
           - .env
        volumes:
            - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db.sql:ro
            - to_do_db:/var/lib/postgresql/data
        networks:
            - to_do
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always

    red:
        container_name: red
        image: redis
        volumes:
            - to_do_state:/data
        networks:
            - to_do
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1s
            timeout: 3s
            retries: 5
        restart: always

    app:
        container_name: to_do_list
        build:
            context: app
        depends_on:
            - db
            - red
        env_file:
            - .env
        networks:
            - to_do
        restart: always

    cleaner:
        container_name: cleaner
        build:
            context: cleaner
        depends_on:
            - db
            - red
        env_file:
            - .env
        networks:
            - to_do
        restart: always

volumes:
    to_do_db:
        name: to_do_db
    to_do_state:
        name: to_do_state

networks:
    to_do:
        name: to_do
        external: True
