FROM python:3.11
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip & pip install --no-cache-dir --upgrade -r requirements.txt
COPY . .
VOLUME [ "/app" ]
ENTRYPOINT ["python3", "main.py"]