FROM python:3.11
WORKDIR /app
COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install -y curl
RUN pip install --upgrade pip & pip install --no-cache-dir --upgrade -r requirements.txt
COPY . .
ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.2.26/supercronic-linux-amd64 \
    SUPERCRONIC=supercronic-linux-amd64 \
    SUPERCRONIC_SHA1SUM=7a79496cf8ad899b99a719355d4db27422396735
RUN curl -fsSLO "$SUPERCRONIC_URL" \
 && echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
 && chmod +x "$SUPERCRONIC" \
 && mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
 && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic \
 && useradd -d /app -r -U sam && chown sam:sam -R /app \
 && chmod u+x main.py
USER sam
ENTRYPOINT ["/bin/bash", "entrypoint.sh"]